# Generated by Django 4.2.10 on 2025-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_favourite_unique_together_favourite_poke_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='poke_id',
            field=models.IntegerField(),
        ),
    ]
