# Generated by Django 4.2.10 on 2025-06-23 05:22

from django.db import migrations

def fix_poke_id(apps, schema_editor):
    Favourite = apps.get_model('app', 'Favourite')  
    for fav in Favourite.objects.filter(poke_id__isnull=True):
        fav.poke_id = fav.id  
        fav.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_favourite_poke_id'),  
    ]

    operations = [
        migrations.RunPython(fix_poke_id),
    ]